# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'RoseCoffeeIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Rosefire', :git => 'https://ada.csse.rose-hulman.edu/rosefire/ios-sdk.git', :tag => '2.1.0'
  pod 'Firebase'
  pod 'Firebase/Database'

end
