target 'RoseCoffeeIOS' do
  use_frameworks!

  pod 'Rosefire', :git => 'https://ada.csse.rose-hulman.edu/rosefire/ios-sdk.git', :tag => '2.1.0'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Cosmos', '~> 8.0'

end
